import z from "zod";
import {DiagnosisCodes, Gender, HealthCheckRating} from "./types";

// ===========================================================================
// New Patient
// ===========================================================================

export const NewPatientSchema = z.object({
    name: z.string(),
    dateOfBirth: z.string().date(),
    ssn: z.string(),
    gender: z.nativeEnum(Gender),
    occupation: z.string()
});

// ===========================================================================
// New Diagnosis Base (id field is generated by server)
// ===========================================================================

const NewDiagnosisBaseSchema = z.object({
    description: z.string(),
    date: z.string().date(),
    specialist: z.string(),
    diagnosisCodes: z.array(z.nativeEnum(DiagnosisCodes)).optional(),
});

// ===========================================================================
// Diagnosis variant - Health Check
// ===========================================================================

const HealthCheckEntrySchema = NewDiagnosisBaseSchema.extend({
    type: z.literal("HealthCheck"),
    healthCheckRating: z.nativeEnum(HealthCheckRating)
});

const DischargeEntrySchema = z.object({
    date: z.string().date(),
    criteria: z.string(),
});

// ===========================================================================
// Diagnosis variant - Hospital
// ===========================================================================

const HospitalEntrySchema = NewDiagnosisBaseSchema.extend({
    type:z.literal("Hospital"),
    discharge: DischargeEntrySchema,
});

// ===========================================================================
// Diagnosis variant - Occupational Health Care
// ===========================================================================

const OccupationalHealthcareEntrySchema = NewDiagnosisBaseSchema.extend({
    type: z.literal("OccupationalHealthcare"),
    employerName: z.string(),
});

// ===========================================================================
// Diagnosis Schema Union
// ===========================================================================

export const NewEntrySchema = z.discriminatedUnion("type", [
    HealthCheckEntrySchema,
    HospitalEntrySchema,
    OccupationalHealthcareEntrySchema,
]);