import axios from 'axios'

const baseUrl = 'http://localhost:3002/anecdotes'

const getAll = async () => {
  const response = await axios.get(baseUrl)
  return response.data
}

const createNew = async (content) => {
  // id is generated by the backend
  const object = {
    content,
    votes:0
  }
  const response = await axios.post(baseUrl, object)
  return response.data
}

const vote = async (anecdote) => {
  const response = await axios.put(`${baseUrl}/${anecdote.id}`, {
    id: anecdote.id,
    content: anecdote.content,
    votes: anecdote.votes+1,
  })
  return response.data
}

export default { getAll, createNew, vote }